require("ysheng26/conform")
require("ysheng26/copilot")
require("ysheng26/gitsigns")
require("ysheng26/lsp")
require("ysheng26/oil")
require("ysheng26/telescope")
require("ysheng26/treesitter")
-- require("ysheng26/vscode")
